server:
  port: 8092

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SCOTT
    password: TIGER
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true

